<?xml version='1.0' encoding='utf-8'?>
<xsl:stylesheet version="2.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
<xsl:import href="_common.xsl" />
<xsl:output method="text" encoding="windows-1252" />
<xsl:template match="info">[Options]<xsl:call-template name="CRLF" />NoConfirmMessageSwitchingDefaultprinter=1<xsl:call-template name="CRLF" />UseAutosave=1<xsl:call-template name="CRLF" />UseAutosaveDirectory=1<xsl:call-template name="CRLF" />AutosaveFilename=dummy<xsl:call-template name="CRLF" />AutosaveFormat=0<xsl:call-template name="CRLF" />StandardAuthor=<xsl:apply-templates select="footer/author"/><xsl:call-template name="CRLF" />StandardSubject=<xsl:apply-templates select="footer/subject"/><xsl:call-template name="CRLF" />StandardTitle=<xsl:apply-templates select="header"/><xsl:call-template name="CRLF" />UseStandardAuthor=1<xsl:call-template name="CRLF" /></xsl:template>
</xsl:stylesheet>
<!-- Stylus Studio meta-information - (c) 2004-2006. Progress Software Corporation. All rights reserved.
<metaInformation>
<scenarios ><scenario default="yes" name="2PDF" userelativepaths="no" externalpreview="no" url="file:///f:/Games/Installs/_Lib/ISM/Files/dummy.xml" htmlbaseurl="" outputurl="" processortype="saxon8" useresolver="yes" profilemode="0" profiledepth="" profilelength="" urlprofilexml="" commandline="" additionalpath="" additionalclasspath="" postprocessortype="none" postprocesscommandline="" postprocessadditionalpath="" postprocessgeneratedext="" validateoutput="no" validator="internal" customvalidator="" ><advancedProp name="sInitialMode" value=""/><advancedProp name="bXsltOneIsOkay" value="true"/><advancedProp name="bSchemaAware" value="true"/><advancedProp name="bXml11" value="false"/><advancedProp name="iValidation" value="0"/><advancedProp name="bExtensions" value="true"/><advancedProp name="iWhitespace" value="0"/><advancedProp name="sInitialTemplate" value=""/><advancedProp name="bTinyTree" value="true"/><advancedProp name="bWarnings" value="true"/><advancedProp name="bUseDTD" value="false"/></scenario></scenarios><MapperMetaTag><MapperInfo srcSchemaPathIsRelative="yes" srcSchemaInterpretAsXML="no" destSchemaPath="" destSchemaRoot="" destSchemaPathIsRelative="yes" destSchemaInterpretAsXML="no" ><SourceSchema srcSchemaPath="dummy.xml" srcSchemaRoot="dummy" AssociatedInstance="" loaderFunction="document" loaderFunctionUsesURI="no"/></MapperInfo><MapperBlockPosition><template match="/"></template><template name="NewTemplate0"></template><template match="text"></template><template match="strong"><block path="strong/xsl:apply&#x2D;templates" x="167" y="18"/></template></MapperBlockPosition><TemplateContext></TemplateContext><MapperFilter side="source"></MapperFilter></MapperMetaTag>
</metaInformation>
-->