using System.Drawing;

using Xps2Img.Shared.TypeConverters;

namespace Xps2Img.Shared.CommandLine
{
    public partial class Options
    {
        public static class Defaults
        {
            public const string FileType        = "png";
            public const string JpegQuality     = "85";
            public const string TiffCompression = "zip";
            public const int    DpiValue        =  120;
            public const string Dpi             = "120";
            public const string FirstPageIndex  = "1";
            public const string PrelimsPrefix   = "$";
            public const int    Processors      = ProcessorsNumberTypeConverter.AutoValue;
            public const string ProcessPriority = ValidationExpressions.AutoValue;
            public const string ImageName       = null;

            public static readonly int JpegQualityValue = IntToString(JpegQuality);

            public static readonly int[] DpiValues              = { 72, 96, 120, 144, 150, 200, 300, 600, 900, 1200, 1600, 1800, 2000, 2350 };
            public static readonly int[] JpegQualityValues      = { 10, 15, 25, 35, 45, 55, 65, 75, 85, 95, 100 };

            public static readonly string[] PrelimsPrefixValues = { "!", "#", "$", ".", "!!!", "###", "$$$", "..." };
            // Generated by Powershell: '{ ' + ((360,480,540,600,720,768,800,854,900,960,1024,1050,1080,1136,1200,1280,1334,1366,1440,1536,1600,1700,1800,1824,1920,2000,2048,2160,2304,2560,2880,3840,4096 | % { "new Size($_, $_)" }) -join ', ') + ' };' | scb
            public static readonly Size[] RequiredSizeValues    = { new Size(360, 360), new Size(480, 480), new Size(540, 540), new Size(600, 600), new Size(720, 720), new Size(768, 768), new Size(800, 800), new Size(854, 854), new Size(900, 900), new Size(960, 960), new Size(1024, 1024), new Size(1050, 1050), new Size(1080, 1080), new Size(1136, 1136), new Size(1200, 1200), new Size(1280, 1280), new Size(1334, 1334), new Size(1366, 1366), new Size(1440, 1440), new Size(1536, 1536), new Size(1600, 1600), new Size(1700, 1700), new Size(1800, 1800), new Size(1824, 1824), new Size(1920, 1920), new Size(2000, 2000), new Size(2048, 2048), new Size(2160, 2160), new Size(2304, 2304), new Size(2560, 2560), new Size(2880, 2880), new Size(3840, 3840), new Size(4096, 4096) };
            public static readonly string[] ImageNameValues     = PrelimsPrefixValues;
        }
    }
}
