//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xps2ImgUI.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Xps2ImgUI.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;About....
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bro&amp;wse Images.
        /// </summary>
        internal static string BrowseConvertedImages {
            get {
                return ResourceManager.GetString("BrowseConvertedImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse &amp;XPS File.
        /// </summary>
        internal static string BrowseXPSFile {
            get {
                return ResourceManager.GetString("BrowseXPSFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convertion is in progress. Would you like to abort it and exit?.
        /// </summary>
        internal static string ClosingQuery {
            get {
                return ResourceManager.GetString("ClosingQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Copy Command Line To Clipboard.
        /// </summary>
        internal static string CopyCommandLineToClipboard {
            get {
                return ResourceManager.GetString("CopyCommandLineToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Copy Images Path To Clipboard.
        /// </summary>
        internal static string CopyConvertedImagesPathToClipboard {
            get {
                return ResourceManager.GetString("CopyConvertedImagesPathToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processor has terminated unexpectedly..
        /// </summary>
        internal static string Error_ProcessorHasTerminated {
            get {
                return ResourceManager.GetString("Error_ProcessorHasTerminated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Help.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Co&amp;mmand Line.
        /// </summary>
        internal static string HideCommandLine {
            get {
                return ResourceManager.GetString("HideCommandLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Convert.
        /// </summary>
        internal static string Launch {
            get {
                return ResourceManager.GetString("Launch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lo&amp;ad Settings....
        /// </summary>
        internal static string LoadSettings {
            get {
                return ResourceManager.GetString("LoadSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error.
        /// </summary>
        internal static string NoExceptionMessage {
            get {
                return ResourceManager.GetString("NoExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset &amp;Settings.
        /// </summary>
        internal static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset &amp;Options.
        /// </summary>
        internal static string ResetOptions {
            get {
                return ResourceManager.GetString("ResetOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset &amp;Parameters.
        /// </summary>
        internal static string ResetParameters {
            get {
                return ResourceManager.GetString("ResetParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Save Settings....
        /// </summary>
        internal static string SaveSettings {
            get {
                return ResourceManager.GetString("SaveSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Co&amp;mmand Line.
        /// </summary>
        internal static string ShowCommandLine {
            get {
                return ResourceManager.GetString("ShowCommandLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} parameter is required..
        /// </summary>
        internal static string SpecifyValue {
            get {
                return ResourceManager.GetString("SpecifyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Stop.
        /// </summary>
        internal static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XPS to Images Converter.
        /// </summary>
        internal static string WindowTitle {
            get {
                return ResourceManager.GetString("WindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launching xps2img... - {0}.
        /// </summary>
        internal static string WindowTitleLaunchingFormat {
            get {
                return ResourceManager.GetString("WindowTitleLaunchingFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {1}% ({2}) [{3}] - {4} - {0}.
        /// </summary>
        internal static string WindowTitleProgressFormat {
            get {
                return ResourceManager.GetString("WindowTitleProgressFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convertion has failed.{0}{0}{1}.
        /// </summary>
        internal static string Xps2ImgError {
            get {
                return ResourceManager.GetString("Xps2ImgError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .x2i.
        /// </summary>
        internal static string XPS2ImgFileExtension {
            get {
                return ResourceManager.GetString("XPS2ImgFileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XPS2Img Files (*.x2i)|*.x2i|.
        /// </summary>
        internal static string XPS2ImgFilesFilter {
            get {
                return ResourceManager.GetString("XPS2ImgFilesFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {1}{0}{0}Make sure that xps2img.exe utility is present in application folder..
        /// </summary>
        internal static string Xps2ImgNotFount {
            get {
                return ResourceManager.GetString("Xps2ImgNotFount", resourceCulture);
            }
        }
    }
}
