//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xps2ImgUI.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Xps2ImgUI.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to d.
        /// </summary>
        internal static string AbbrevDays {
            get {
                return ResourceManager.GetString("AbbrevDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hr.
        /// </summary>
        internal static string AbbrevHours {
            get {
                return ResourceManager.GetString("AbbrevHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to min.
        /// </summary>
        internal static string AbbrevMinutes {
            get {
                return ResourceManager.GetString("AbbrevMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to p.
        /// </summary>
        internal static string AbbrevPage {
            get {
                return ResourceManager.GetString("AbbrevPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pp.
        /// </summary>
        internal static string AbbrevPages {
            get {
                return ResourceManager.GetString("AbbrevPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sec.
        /// </summary>
        internal static string AbbrevSeconds {
            get {
                return ResourceManager.GetString("AbbrevSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;About....
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Al&amp;ways confirm and do not ask again.
        /// </summary>
        internal static string AlwaysConfirmAndDoNotAskAgain {
            get {
                return ResourceManager.GetString("AlwaysConfirmAndDoNotAskAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A&amp;uto Save Settings.
        /// </summary>
        internal static string AutoSaveSettings {
            get {
                return ResourceManager.GetString("AutoSaveSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go &amp;Back to Application.
        /// </summary>
        internal static string BackToApplication {
            get {
                return ResourceManager.GetString("BackToApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bro&amp;wse Images.
        /// </summary>
        internal static string BrowseImages {
            get {
                return ResourceManager.GetString("BrowseImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse I&amp;mages Folder.
        /// </summary>
        internal static string BrowseImagesFolder {
            get {
                return ResourceManager.GetString("BrowseImagesFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse &amp;XPS File.
        /// </summary>
        internal static string BrowseXPSFile {
            get {
                return ResourceManager.GetString("BrowseXPSFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \n\n● Cancel or Esc reverts to previous valid value.\n● OK returns to value editing..
        /// </summary>
        internal static string CancelToUsePreviousValidValue {
            get {
                return ResourceManager.GetString("CancelToUsePreviousValidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for &amp;Updates.
        /// </summary>
        internal static string CheckForUpdates {
            get {
                return ResourceManager.GetString("CheckForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Application Confirmation.
        /// </summary>
        internal static string CloseApplicationConfirmation {
            get {
                return ResourceManager.GetString("CloseApplicationConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently executing conversion will be aborted..
        /// </summary>
        internal static string ClosingConfirmation {
            get {
                return ResourceManager.GetString("ClosingConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conversion Failed.
        /// </summary>
        internal static string ConversionFailed {
            get {
                return ResourceManager.GetString("ConversionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conversion will be stopped..
        /// </summary>
        internal static string ConversionStopConfirmation {
            get {
                return ResourceManager.GetString("ConversionStopConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conversion was aborted by user..
        /// </summary>
        internal static string ConversionWasAbortedByUser {
            get {
                return ResourceManager.GetString("ConversionWasAbortedByUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Copy Command Line To Clipboard.
        /// </summary>
        internal static string CopyCommandLineToClipboard {
            get {
                return ResourceManager.GetString("CopyCommandLineToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Copy Images Folder Path To Clipboard.
        /// </summary>
        internal static string CopyImagesFolderPathToClipboard {
            get {
                return ResourceManager.GetString("CopyImagesFolderPathToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy UI &amp;Batch Command Line To Clipboard.
        /// </summary>
        internal static string CopyUIBatchCommandLineToClipboard {
            get {
                return ResourceManager.GetString("CopyUIBatchCommandLineToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy UI Batch Command Line Without &amp;Error Handling To Clipboard.
        /// </summary>
        internal static string CopyUIBatchCommandLineWithoutErrorHandlingToClipboard {
            get {
                return ResourceManager.GetString("CopyUIBatchCommandLineWithoutErrorHandlingToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy &amp;UI Command Line To Clipboard.
        /// </summary>
        internal static string CopyUICommandLineToClipboard {
            get {
                return ResourceManager.GetString("CopyUICommandLineToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy XP&amp;S File Path To Clipboard.
        /// </summary>
        internal static string CopyXPSFilePathToClipboard {
            get {
                return ResourceManager.GetString("CopyXPSFilePathToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converted images will be deleted..
        /// </summary>
        internal static string DeleteConvertedImagesConfirmation {
            get {
                return ResourceManager.GetString("DeleteConvertedImagesConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Images Confirmation.
        /// </summary>
        internal static string DeleteImagesConfirmation {
            get {
                return ResourceManager.GetString("DeleteImagesConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document has no pages. Nothing to convert..
        /// </summary>
        internal static string DocumentHasNoPages {
            get {
                return ResourceManager.GetString("DocumentHasNoPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Failed.
        /// </summary>
        internal static string DownloadFailed {
            get {
                return ResourceManager.GetString("DownloadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download failed. Application Web site will be opened..
        /// </summary>
        internal static string DownloadFailedWarning {
            get {
                return ResourceManager.GetString("DownloadFailedWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Edit Parameter.
        /// </summary>
        internal static string EditParameter {
            get {
                return ResourceManager.GetString("EditParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  ● {0:00}:{1:00}:{2:00} ● {6}/{7} ● {3}{4}/{5} ●.
        /// </summary>
        internal static string ElapsedTimeTextTemplate {
            get {
                return ResourceManager.GetString("ElapsedTimeTextTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  ● {0:00}:{1:00}:{2:00} ● {6}/{7} ●.
        /// </summary>
        internal static string ElapsedTimeTextTemplateShort {
            get {
                return ResourceManager.GetString("ElapsedTimeTextTemplateShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Files (*.*)|*.*.
        /// </summary>
        internal static string FilterAllFiles {
            get {
                return ResourceManager.GetString("FilterAllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XPS2Img Files (*.x2i)|*.x2i|.
        /// </summary>
        internal static string FilterXPS2ImgFiles {
            get {
                return ResourceManager.GetString("FilterXPS2ImgFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Help.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Co&amp;mmand Line.
        /// </summary>
        internal static string HideCommandLine {
            get {
                return ResourceManager.GetString("HideCommandLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide &amp;Details.
        /// </summary>
        internal static string HideDetails {
            get {
                return ResourceManager.GetString("HideDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Convert.
        /// </summary>
        internal static string Launch {
            get {
                return ResourceManager.GetString("Launch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lo&amp;ad Settings....
        /// </summary>
        internal static string LoadSettings {
            get {
                return ResourceManager.GetString("LoadSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Settings.
        /// </summary>
        internal static string LoadSettingsTitle {
            get {
                return ResourceManager.GetString("LoadSettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Version Available.
        /// </summary>
        internal static string NewUpdateAvailable {
            get {
                return ResourceManager.GetString("NewUpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New version is available. Application will be updated..
        /// </summary>
        internal static string NewUpdateIsAvailable {
            get {
                return ResourceManager.GetString("NewUpdateIsAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;No, Go Back to Application.
        /// </summary>
        internal static string NoBackToApplication {
            get {
                return ResourceManager.GetString("NoBackToApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No exception details present..
        /// </summary>
        internal static string NoExceptionDetailsPresent {
            get {
                return ResourceManager.GetString("NoExceptionDetailsPresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;No, Start Conversion Over.
        /// </summary>
        internal static string NoStartConversionOver {
            get {
                return ResourceManager.GetString("NoStartConversionOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}/{1}.
        /// </summary>
        internal static string PageOfPages {
            get {
                return ResourceManager.GetString("PageOfPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pages specified are out of document pages range. {0} is the last one..
        /// </summary>
        internal static string PagesSpecifiedAreOutOfRange {
            get {
                return ResourceManager.GetString("PagesSpecifiedAreOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This parameter is required and could not be empty..
        /// </summary>
        internal static string ParameterIsRequired {
            get {
                return ResourceManager.GetString("ParameterIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Preferences....
        /// </summary>
        internal static string Preferences {
            get {
                return ResourceManager.GetString("Preferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press OK to proceed..
        /// </summary>
        internal static string PressToProceedMessage {
            get {
                return ResourceManager.GetString("PressToProceedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xps2img.exe processor application has terminated unexpectedly..
        /// </summary>
        internal static string ProcessorHasTerminated {
            get {
                return ResourceManager.GetString("ProcessorHasTerminated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Remember choice and do not ask again.
        /// </summary>
        internal static string RememberChoiceAndDoNotAskAgain {
            get {
                return ResourceManager.GetString("RememberChoiceAndDoNotAskAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset &amp;Settings.
        /// </summary>
        internal static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset &amp;Options.
        /// </summary>
        internal static string ResetOptions {
            get {
                return ResourceManager.GetString("ResetOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset &amp;Parameters.
        /// </summary>
        internal static string ResetParameters {
            get {
                return ResourceManager.GetString("ResetParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset To &amp;Default.
        /// </summary>
        internal static string ResetToDefault {
            get {
                return ResourceManager.GetString("ResetToDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume Conversion Confirmation.
        /// </summary>
        internal static string ResumeConversionConfirmation {
            get {
                return ResourceManager.GetString("ResumeConversionConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to resume last conversion instead of starting new one?.
        /// </summary>
        internal static string ResumeLastConversionSuggestion {
            get {
                return ResourceManager.GetString("ResumeLastConversionSuggestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Save Settings....
        /// </summary>
        internal static string SaveSettings {
            get {
                return ResourceManager.GetString("SaveSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Settings.
        /// </summary>
        internal static string SaveSettingsTitle {
            get {
                return ResourceManager.GetString("SaveSettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S&amp;horten Image Extension.
        /// </summary>
        internal static string ShortenImageExtension {
            get {
                return ResourceManager.GetString("ShortenImageExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Co&amp;mmand Line.
        /// </summary>
        internal static string ShowCommandLine {
            get {
                return ResourceManager.GetString("ShowCommandLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show &amp;Details.
        /// </summary>
        internal static string ShowDetails {
            get {
                return ResourceManager.GetString("ShowDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} parameter is required..
        /// </summary>
        internal static string SpecifyValue {
            get {
                return ResourceManager.GetString("SpecifyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Stop.
        /// </summary>
        internal static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Conversion Confirmation.
        /// </summary>
        internal static string StopConversionConfirmation {
            get {
                return ResourceManager.GetString("StopConversionConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to start/wait &quot;&quot; {0} -b.
        /// </summary>
        internal static string UIBatchCommandLine {
            get {
                return ResourceManager.GetString("UIBatchCommandLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  &amp; if errorlevel 1 exit /b.
        /// </summary>
        internal static string UIBatchCommandLineErrorHandling {
            get {
                return ResourceManager.GetString("UIBatchCommandLineErrorHandling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected: Conversion is in progress..
        /// </summary>
        internal static string UnexpectedConversionIsInProgress {
            get {
                return ResourceManager.GetString("UnexpectedConversionIsInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected Error Occured.
        /// </summary>
        internal static string UnexpectedErrorOccured {
            get {
                return ResourceManager.GetString("UnexpectedErrorOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected: Resume is not available..
        /// </summary>
        internal static string UnexpectedResumeIsNotAvailable {
            get {
                return ResourceManager.GetString("UnexpectedResumeIsNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Failed.
        /// </summary>
        internal static string UpdateFailed {
            get {
                return ResourceManager.GetString("UpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update failed. Application Web site will be opened..
        /// </summary>
        internal static string UpdateFailedWarning {
            get {
                return ResourceManager.GetString("UpdateFailedWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no new version available at this time..
        /// </summary>
        internal static string UpdateNoNewVersionAvailable {
            get {
                return ResourceManager.GetString("UpdateNoNewVersionAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updates Check Failed.
        /// </summary>
        internal static string UpdatesCheckFailed {
            get {
                return ResourceManager.GetString("UpdatesCheckFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for updates failed. Application Web site will be opened..
        /// </summary>
        internal static string UpdatesCheckFailedWarning {
            get {
                return ResourceManager.GetString("UpdatesCheckFailedWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Validation Error.
        /// </summary>
        internal static string ValidationError {
            get {
                return ResourceManager.GetString("ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Edit Value.
        /// </summary>
        internal static string ValueEdit {
            get {
                return ResourceManager.GetString("ValueEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value is not valid integer number.
        /// </summary>
        internal static string ValueIsNotValidIntegerNumber {
            get {
                return ResourceManager.GetString("ValueIsNotValidIntegerNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Revert Value.
        /// </summary>
        internal static string ValueRevert {
            get {
                return ResourceManager.GetString("ValueRevert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a href=&quot;http://sourceforge.net/projects/xps2img/files/&quot;&gt;Visit download page&lt;/a&gt;.
        /// </summary>
        internal static string VisitDownloadPage {
            get {
                return ResourceManager.GetString("VisitDownloadPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ● .
        /// </summary>
        internal static string WhatsNewBullet {
            get {
                return ResourceManager.GetString("WhatsNewBullet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1:&apos;(&apos;d MMMM yyyy&apos;):&apos;}.
        /// </summary>
        internal static string WhatsNewDateFormat {
            get {
                return ResourceManager.GetString("WhatsNewDateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///What&apos;s new in version {0}
        ///
        ///.
        /// </summary>
        internal static string WhatsNewFormat {
            get {
                return ResourceManager.GetString("WhatsNewFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XPS to Images Converter.
        /// </summary>
        internal static string WindowTitle {
            get {
                return ResourceManager.GetString("WindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launching xps2img... - {0}.
        /// </summary>
        internal static string WindowTitleLaunchingFormat {
            get {
                return ResourceManager.GetString("WindowTitleLaunchingFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {1}% ({2}) [{3}] - {4} - {0}.
        /// </summary>
        internal static string WindowTitleProgressFormat {
            get {
                return ResourceManager.GetString("WindowTitleProgressFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to abort conversion and close application?.
        /// </summary>
        internal static string WouldYouLikeToAbortConversionAndCloseApplication {
            get {
                return ResourceManager.GetString("WouldYouLikeToAbortConversionAndCloseApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to check for updates manually?.
        /// </summary>
        internal static string WouldYouLikeToCheckForUpdatesManually {
            get {
                return ResourceManager.GetString("WouldYouLikeToCheckForUpdatesManually", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to delete images?.
        /// </summary>
        internal static string WouldYouLikeToDeleteImages {
            get {
                return ResourceManager.GetString("WouldYouLikeToDeleteImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to download and update manually?.
        /// </summary>
        internal static string WouldYouLikeToDownloadAndUpdateManually {
            get {
                return ResourceManager.GetString("WouldYouLikeToDownloadAndUpdateManually", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to download it and update application?.
        /// </summary>
        internal static string WouldYouLikeToDownloadItAndUpdateApplication {
            get {
                return ResourceManager.GetString("WouldYouLikeToDownloadItAndUpdateApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to download update manually?.
        /// </summary>
        internal static string WouldYouLikeToDownloadUpdateManually {
            get {
                return ResourceManager.GetString("WouldYouLikeToDownloadUpdateManually", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to stop conversion?.
        /// </summary>
        internal static string WouldYouLikeToStopConversion {
            get {
                return ResourceManager.GetString("WouldYouLikeToStopConversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .x2i.
        /// </summary>
        internal static string XPS2ImgFileExtension {
            get {
                return ResourceManager.GetString("XPS2ImgFileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {1}{0}{0}Please make sure that xps2img.exe utility is present into the application folder..
        /// </summary>
        internal static string Xps2ImgNotFount {
            get {
                return ResourceManager.GetString("Xps2ImgNotFount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Yes, Abort and Close.
        /// </summary>
        internal static string YesAbortAndClose {
            get {
                return ResourceManager.GetString("YesAbortAndClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Yes, Check for Updates Manually.
        /// </summary>
        internal static string YesCheckForUpdatesManually {
            get {
                return ResourceManager.GetString("YesCheckForUpdatesManually", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Yes, Delete Images.
        /// </summary>
        internal static string YesDeleteImages {
            get {
                return ResourceManager.GetString("YesDeleteImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Yes, Download and Update.
        /// </summary>
        internal static string YesDownloadAndUpdate {
            get {
                return ResourceManager.GetString("YesDownloadAndUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Yes, Download and Update Manually.
        /// </summary>
        internal static string YesDownloadAndUpdateManually {
            get {
                return ResourceManager.GetString("YesDownloadAndUpdateManually", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Yes, Download Update Manually.
        /// </summary>
        internal static string YesDownloadManually {
            get {
                return ResourceManager.GetString("YesDownloadManually", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Yes, Resume Conversion.
        /// </summary>
        internal static string YesResumeConversion {
            get {
                return ResourceManager.GetString("YesResumeConversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Yes, Stop Conversion.
        /// </summary>
        internal static string YesStopConversion {
            get {
                return ResourceManager.GetString("YesStopConversion", resourceCulture);
            }
        }
    }
}
