//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommandLine.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CommandLine.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///One of:
        ///  {0}.
        /// </summary>
        internal static string Format_Alternatives {
            get {
                return ResourceManager.GetString("Format_Alternatives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///  .
        /// </summary>
        internal static string Format_AlternativesSeparator {
            get {
                return ResourceManager.GetString("Format_AlternativesSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///  {0} by default.
        /// </summary>
        internal static string Format_DefaultValue {
            get {
                return ResourceManager.GetString("Format_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {1}.
        /// </summary>
        internal static string Format_LongOpt {
            get {
                return ResourceManager.GetString("Format_LongOpt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  [options].
        /// </summary>
        internal static string Format_OptionalOptions {
            get {
                return ResourceManager.GetString("Format_OptionalOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, {1}.
        /// </summary>
        internal static string Format_ShortAndLongOpt {
            get {
                return ResourceManager.GetString("Format_ShortAndLongOpt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage: {0}.
        /// </summary>
        internal static string Format_Usage {
            get {
                return ResourceManager.GetString("Format_Usage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mandatory arguments to long options are mandatory for short options too.
        ///.
        /// </summary>
        internal static string Message_MandatoryArgs {
            get {
                return ResourceManager.GetString("Message_MandatoryArgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to must be specified.
        /// </summary>
        internal static string Message_OptNotSpecified {
            get {
                return ResourceManager.GetString("Message_OptNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   .
        /// </summary>
        internal static string Message_OptPadLeft {
            get {
                return ResourceManager.GetString("Message_OptPadLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to value is not in list (see help).
        /// </summary>
        internal static string Validation_EnumValidator {
            get {
                return ResourceManager.GetString("Validation_EnumValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to value should be between {0} and {1}.
        /// </summary>
        internal static string Validation_IntValidator {
            get {
                return ResourceManager.GetString("Validation_IntValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No validator found for validation expression.
        /// </summary>
        internal static string Validation_NoValidator {
            get {
                return ResourceManager.GetString("Validation_NoValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to value format is incorrect.
        /// </summary>
        internal static string Validation_RegexValidator {
            get {
                return ResourceManager.GetString("Validation_RegexValidator", resourceCulture);
            }
        }
    }
}
