//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1022
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xps2Img.Shared.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new Xps2Img.Shared.Localization.SingleAssemblyResourceManager(typeof(Strings));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Files (*.*)|*.*.
        /// </summary>
        internal static string FilterAllFiles {
            get {
                return ResourceManager.GetString("FilterAllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executable Files (*.exe)|*.exe|.
        /// </summary>
        internal static string FilterExeFiles {
            get {
                return ResourceManager.GetString("FilterExeFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XPS Files (*.xps)|*.xps|.
        /// </summary>
        internal static string FilterXPSFiles {
            get {
                return ResourceManager.GetString("FilterXPSFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BMP.
        /// </summary>
        internal static string ImageType_BmpValue {
            get {
                return ResourceManager.GetString("ImageType_BmpValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GIF.
        /// </summary>
        internal static string ImageType_GifValue {
            get {
                return ResourceManager.GetString("ImageType_GifValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JPEG.
        /// </summary>
        internal static string ImageType_JpegValue {
            get {
                return ResourceManager.GetString("ImageType_JpegValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PNG.
        /// </summary>
        internal static string ImageType_PngValue {
            get {
                return ResourceManager.GetString("ImageType_PngValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TIFF.
        /// </summary>
        internal static string ImageType_TiffValue {
            get {
                return ResourceManager.GetString("ImageType_TiffValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do Nothing.
        /// </summary>
        internal static string PostAction_DoNothingValue {
            get {
                return ResourceManager.GetString("PostAction_DoNothingValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string PostAction_ExitValue {
            get {
                return ResourceManager.GetString("PostAction_ExitValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hibernate.
        /// </summary>
        internal static string PostAction_HibernateValue {
            get {
                return ResourceManager.GetString("PostAction_HibernateValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LogOff.
        /// </summary>
        internal static string PostAction_LogOffValue {
            get {
                return ResourceManager.GetString("PostAction_LogOffValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reboot.
        /// </summary>
        internal static string PostAction_RebootValue {
            get {
                return ResourceManager.GetString("PostAction_RebootValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shutdown.
        /// </summary>
        internal static string PostAction_ShutdownValue {
            get {
                return ResourceManager.GetString("PostAction_ShutdownValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sleep.
        /// </summary>
        internal static string PostAction_SleepValue {
            get {
                return ResourceManager.GetString("PostAction_SleepValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Above Normal.
        /// </summary>
        internal static string ProcessPriorityClass_AboveNormalValue {
            get {
                return ResourceManager.GetString("ProcessPriorityClass_AboveNormalValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto.
        /// </summary>
        internal static string ProcessPriorityClass_AutoValue {
            get {
                return ResourceManager.GetString("ProcessPriorityClass_AutoValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Below Normal.
        /// </summary>
        internal static string ProcessPriorityClass_BelowNormalValue {
            get {
                return ResourceManager.GetString("ProcessPriorityClass_BelowNormalValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High.
        /// </summary>
        internal static string ProcessPriorityClass_HighValue {
            get {
                return ResourceManager.GetString("ProcessPriorityClass_HighValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idle.
        /// </summary>
        internal static string ProcessPriorityClass_IdleValue {
            get {
                return ResourceManager.GetString("ProcessPriorityClass_IdleValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        internal static string ProcessPriorityClass_NormalValue {
            get {
                return ResourceManager.GetString("ProcessPriorityClass_NormalValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Executable File.
        /// </summary>
        internal static string SelectExecutableFile {
            get {
                return ResourceManager.GetString("SelectExecutableFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select XPS File.
        /// </summary>
        internal static string SelectXpsFile {
            get {
                return ResourceManager.GetString("SelectXpsFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify folder to store images. If not set new folder named as document will be created in folder where document is..
        /// </summary>
        internal static string SpecifyImagesFolder {
            get {
                return ResourceManager.GetString("SpecifyImagesFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CCITT3.
        /// </summary>
        internal static string TiffCompressOption_Ccitt3Value {
            get {
                return ResourceManager.GetString("TiffCompressOption_Ccitt3Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CCITT4.
        /// </summary>
        internal static string TiffCompressOption_Ccitt4Value {
            get {
                return ResourceManager.GetString("TiffCompressOption_Ccitt4Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LZW.
        /// </summary>
        internal static string TiffCompressOption_LzwValue {
            get {
                return ResourceManager.GetString("TiffCompressOption_LzwValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string TiffCompressOption_NoneValue {
            get {
                return ResourceManager.GetString("TiffCompressOption_NoneValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RLE.
        /// </summary>
        internal static string TiffCompressOption_RleValue {
            get {
                return ResourceManager.GetString("TiffCompressOption_RleValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZIP.
        /// </summary>
        internal static string TiffCompressOption_ZipValue {
            get {
                return ResourceManager.GetString("TiffCompressOption_ZipValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value is not valid integer number.
        /// </summary>
        internal static string ValueIsNotValidIntegerNumber {
            get {
                return ResourceManager.GetString("ValueIsNotValidIntegerNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
